version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: entrevista_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: entrevista
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./storage/database:/var/lib/postgresql/data

  laravel:
    image: php:8.2-apache
    container_name: entrevista_laravel
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./apache/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=entrevista
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    command: bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_pgsql && apache2-foreground"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres
